version: "3.9"
services:
  web:
    image: alfg/nginx-rtmp:latest
    ports:
      - "1935:1935"
      - "8080:80"
    environment: 
      - STREAM_KEY_CHATURBATE
      - STREAM_KEY_STRIPCHAT
      - STREAM_KEY_MFC
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template
